// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn4JF1Xw-aKCvgWjj8_ezooSsyfXpvUHA',
    appId: '1:940197186244:web:c2f0764d223b284ed1d791',
    messagingSenderId: '940197186244',
    projectId: 'climbkit-f6608',
    authDomain: 'climbkit-f6608.firebaseapp.com',
    storageBucket: 'climbkit-f6608.appspot.com',
    measurementId: 'G-GHFDWZZ3Z5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn4JF1Xw-aKCvgWjj8_ezooSsyfXpvUHA',
    appId: '1:940197186244:android:17e19dfc82cc0f30d1d791',
    messagingSenderId: '940197186244',
    projectId: 'climbkit-f6608',
    storageBucket: 'climbkit-f6608.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn4JF1Xw-aKCvgWjj8_ezooSsyfXpvUHA',
    appId: '1:940197186244:ios:0015c52f986a141ad1d791',
    messagingSenderId: '940197186244',
    projectId: 'climbkit-f6608',
    storageBucket: 'climbkit-f6608.appspot.com',
    iosBundleId: 'com.example.climbkit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn4JF1Xw-aKCvgWjj8_ezooSsyfXpvUHA',
    appId: '1:940197186244:ios:0015c52f986a141ad1d791',
    messagingSenderId: '940197186244',
    projectId: 'climbkit-f6608',
    storageBucket: 'climbkit-f6608.appspot.com',
    iosBundleId: 'com.example.climbkit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDn4JF1Xw-aKCvgWjj8_ezooSsyfXpvUHA',
    appId: '1:940197186244:web:c2f0764d223b284ed1d791',
    messagingSenderId: '940197186244',
    projectId: 'climbkit-f6608',
    authDomain: 'climbkit-f6608.firebaseapp.com',
    storageBucket: 'climbkit-f6608.appspot.com',
    measurementId: 'G-GHFDWZZ3Z5',
  );
}
